Discurage interrupting FAI

diff --git a/bin/fai b/bin/fai
--- a/bin/fai
+++ b/bin/fai
@@ -94,7 +94,7 @@ fai_init() {
     if [ $do_init_tasks -eq 1 ]; then
         trap 'echo "Now rebooting";faireboot' INT QUIT
     else
-        trap "echo 'Aborted';rm -f $stamp" INT QUIT
+        trap "echo 'Aborted';rm -f $stamp" QUIT
     fi
 
     if [ $do_init_tasks -eq 1 ]; then
